version: 2.1 # use CircleCI 2.0

workflows:
  version: 2
  "Build, Test & Run":
    jobs:
      - build:
          requires:
            - test
      - test
      - deploy_dev:
          requires:
            - build
          context: aws-credentials
      - deploy_uat:
          requires:
            - deploy_dev
          context: aws-credentials
      - deploy_qa:
          requires:
            - deploy_dev
          context: aws-credentials
      - deploy_preprod:
          type: approval
          requires:
            - deploy_qa
            - deploy_uat
          context: aws-credentials
      - deploy_prd:
          type: approval
          requires:
            - deploy_preprod
          context: aws-credentials


jobs:
  build:

    docker:
      - image: circleci/openjdk:8-jdk-stretch

    steps:
      - checkout
      - restore_cache:
          key: Calculator-{{ checksum "pom.xml" }}
      - save_cache:
          paths:
            - ~/.m2
          key: Calculator-{{ checksum "pom.xml" }}
      - run: mvn package

      - persist_to_workspace:
          root: /home/circleci/project/target
          paths:
            - Calculator-1.0-SNAPSHOT.jar

  deploy_dev:
    docker:
      - image: circleci/node:10.15

    steps:
      - checkout
      - attach_workspace:
          at: target
      - deploy:
          command: npx serverless deploy --stage dev

  deploy_uat:
    docker:
      - image: circleci/node:10.15

    steps:
      - checkout
      - attach_workspace:
          at: target
      - deploy:
          command: echo "UAT Deploy Completed"

  deploy_qa:
    docker:
      - image: circleci/node:10.15

    steps:
      - checkout
      - attach_workspace:
          at: target
      - deploy:
          command: echo "QA Deploy Completed"

  deploy_preprod:
    docker:
      - image: circleci/node:10.15

    steps:
      - checkout
      - attach_workspace:
          at: target
      - deploy:
          command: echo "Pre Prod Deploy Completed"

  deploy_prd:
    docker:
      - image: circleci/node:10.15

    steps:
      - checkout
      - attach_workspace:
          at: target
      - deploy:
          command: echo "Pre Prod Deploy Completed"

  test:
    docker:
      - image: circleci/openjdk:8-jdk-stretch
    steps:
      - checkout
      - restore_cache:
          key: Calculator-{{ checksum "pom.xml" }}
      - save_cache:
          paths:
            - ~/.m2
          key: Calculator-{{ checksum "pom.xml" }}
      - run: mvn test

