version: 2.1 # use CircleCI 2.0

orbs:
  queue: eddiewebb/queue@1.1.4

workflows:
  version: 2
  "Build, Test & Run":
    jobs:
      - queue/block_workflow:
          time: '10'
          consider-branch: false
      - build:
          requires:
            - test
          context: aws-credentials
      - test:
          requires:
            - queue/block_workflow
      - deploy_dev:
          requires:
            - build
          context: aws-credentials
jobs: # a collection of steps
  build: # runs not using Workflows must have a `build` job as entry point

    docker:
      - image: softinstigate/serverless

    steps:
      - checkout
      - restore_cache:
          key: Calculator-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - save_cache: #
          paths:
            - ~/.m2
          key: Calculator-{{ checksum "pom.xml" }}
      - run: mvn package
      - run: cd ..

      - persist_to_workspace:
          root: /root/project
          paths:
            - target

      - store_test_results:
          path: target/surefire-reports

      - store_artifacts:
          path: target/Calculator-1.0-SNAPSHOT.jar


  deploy_dev:
    docker:
      - image: circleci/node:10.15
      - image: circleci/openjdk:8-jdk-stretch

    steps:
      - attach_workspace:
          at: Jackil-Rajnicant
      - run: cd Jackil-Rajnicant
      - run: ls -al

      - deploy:
          command: npx serverless deploy --stage dev

  test:
    working_directory: ~/Jackil-Rajnicant/Calculator

    docker:
      - image: circleci/openjdk:8-jdk-stretch

    steps:
      - checkout

      - run: mvn test

