version: 2.1 # use CircleCI 2.0

environment:
  BRANCH: master

executors:
  node-executor:
    docker:
      - image: circleci/node:10.15
  openjdk-executor:
    docker:
      - image: circleci/openjdk:8-jdk-stretch

workflows:
  version: 2
  "Build, Test & Run":
    jobs:
      - build:
          filters:
            branches:
              only: master
      - deploy_dev:
          requires:
            - build
          context: aws-credentials
      - deploy_uat:
          requires:
            - deploy_dev
          context: aws-credentials
      - deploy_qa:
          requires:
            - deploy_dev
          context: aws-credentials
      - deploy_sit:
          requires:
            - deploy_dev
          context: aws-credentials
      - deploy_perf:
          requires:
            - deploy_dev
          context: aws-credentials
      - deploy_support:
          requires:
            - deploy_prd
          context: aws-credentials
      - deploy_preprod:
          type: approval
          requires:
            - deploy_qa
            - deploy_uat
          context: aws-credentials
      - deploy_prd:
          type: approval
          requires:
            - deploy_preprod
          context: aws-credentials


jobs:
  buildRun:

    executor: openjdk-executor

    steps:
      - checkout
      - restore_cache:
          key: Calculator-{{ checksum "pom.xml" }}
      - save_cache:
          paths:
            - ~/.m2
          key: Calculator-{{ checksum "pom.xml" }}
      - run: mvn package

      - persist_to_workspace:
          root: /home/circleci/project/target
          paths:
            - Calculator-1.0-SNAPSHOT.jar

  deploy_dev:
    executor: node-executor

    steps:
      - checkout
      - attach_workspace:
          at: target
      - deploy:
          command: npx serverless deploy --stage dev

  deploy_uat:
    executor: node-executor

    steps:
      - checkout
      - attach_workspace:
          at: target
      - deploy:
          command: echo "UAT Deploy Completed"

  deploy_qa:
    executor: node-executor

    steps:
      - checkout
      - attach_workspace:
          at: target
      - deploy:
          command: echo "QA Deploy Completed"

  deploy_sit:
    executor: node-executor

    steps:
      - checkout
      - attach_workspace:
          at: target
      - deploy:
          command: echo "SIT Deploy Completed"

  deploy_support:
    executor: node-executor

    steps:
      - checkout
      - attach_workspace:
          at: target
      - deploy:
          command: echo "SUPPORT Deploy Completed"

  deploy_perf:
    executor: node-executor

    steps:
      - checkout
      - attach_workspace:
          at: target
      - deploy:
          command: echo "PERF Deploy Completed"

  deploy_preprod:
    executor: node-executor

    steps:
      - checkout
      - attach_workspace:
          at: target
      - deploy:
          command: echo "Pre Prod Deploy Completed"

  deploy_prd:
    executor: node-executor

    steps:
      - checkout
      - attach_workspace:
          at: target
      - deploy:
          command: echo "Pre Prod Deploy Completed"


